### ISSUE TITLE
Eldat USB Stick: Online store 

### ISSUE THREAD

**Issue by ced2git** [marcselis/Easywave2MQTT#5]
Hello, 

i would like to test your software but cannot find the USB stick. 

Where have ordered the stick ? 

Thanks
Cedric

**Comment by marcselis** [comment]
See the [this topic on the HA community](https://community.home-assistant.io/t/new-add-on-to-add-support-for-easywave-devices).  There is a post on there of me on there with some links.
For the rest is google your friend.
