### ISSUE TITLE
Add support for Blinds

### ISSUE THREAD

**Issue by marcselis** [marcselis/Easywave2MQTT#6]
Please add support for Easywave blinds.

**Comment by sebatro** [comment]
Hi Marc,
could you help me getting the blinds (driven by easywave RCJ01) into homeassistant. I already included the existing sender (remotes) with three buttons. I also got a MQTT entity which sets am MQTT command, named "button_A_press". 
I saw you have also included blinds but when I set type to blind it does not get recognized by your app.

Any suggestion or guide into the right direction would be really appreciate.

**Comment by marcselis** [comment]
Hi,

I described extensively how to configure blinds on the topic about this plug-in in the [Home Assistant Community](https://community.home-assistant.io/t/new-add-on-to-add-support-for-easywave-devices/385609/40?u=marcselis).

Please check there first and let me know whether it helped or not.

**Comment by marcselis** [comment]
Some more information on how the plug-in works and how to control EasyWave devices from Home Assistant can be found [here](https://github.com/marcselis/Easywave2MQTT/issues/7#issuecomment-1745482047)

**Comment by marcselis** [comment]
Blinds (or Covers as they are named in Home Assistant) should be supported in V1.0.
They report 5 states: `opening`, `open`, `closing`, `closed` & `stopped`.  As EasyWave devices do not report their status, the transition from `opening` to `open` and from `closing` to `closed` is currently done with a fixed 10 second delay.

If you press the `stop` button during opening & closing actions, the state `stopped` is reported, but unfortunately Home Assistant does not reflect that state correctly. 
When the previous state was `opening`, it considers them `open` and will not allow to open them further.
When the previous state was `closing`, HA considers them `closed` and will not allow to close them further.
